#ifndef __BUSENGINEPRI__
#define __BUSENGINEPRI__
typedef struct
{
	qint32 Size;//4
	qint8 Command; //1
	char Data[0];
}__attribute__((packed)) COMMAND_DATA_PACKET; //Size = 8, Data[1] + 2 free bytes = 3 free bytes

typedef struct 
{
	qint32 DeviceID; //4
	qint32 Size; //4
	char Data[0]; //1
}__attribute__((packed)) DEVICE_DATA_PACKET;

typedef enum
{
	CLIENT_CONNECT = 0,
	CLIENT_DISCONNECT = 1,
	CLIENT_KEEPALIVE = 2,
	REQUEST_DEVICES = 3,
	CONNECT_TO_DEVICE = 4,
	DISCONNECT_FROM_DEVICE = 5,
	DEVICE_DATA = 6,
	REQUEST_VERSION = 7,
	DEVICE_LIST_CHANGED = 8,
	DEVICE_RAW_DATA = 9,
	OPEN_ALL_DEVICES = 10,
	CLOSE_ALL_DEVICES = 11,
	OPEN_DEVICE_BY_NAME = 12,
	CLOSE_DEVICE_BY_NAME = 13,
	OPEN_DEVICE_BY_ID = 14,
	CLOSE_DEVICE_BY_ID = 15,
	AM_I_FIRST = 16,
	SET_FILTER = 17,
	CLOSE_FILTER = 18,
	REQUEST_FILTERS = 19,
	GLOBAL_ENABLE_FILTERS = 20,
	FTDI_DATA = 21,
	FTDI_DATA_R = 22,
	CREATE_VS = 23,
	DESTROY_VS = 24,
	UPDATE_TIMESTAMP = 25
} COMMAND;
#endif
